### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by foobear**
Let's maybe talk about these. :)

### CODE REVIEW

**Comment by codener** [comment]
Nothing to say about this. Agreed.

**Comment by kratob** [comment]
The additional blank lines were intended to separate logical blocks "private variables" vs "bindable members" vs "bindable functions" etc, so they all were intentional.

Should I make this explicit, or do your still prefer to just drop them?

**Comment by kratob** [comment]
(Rest is merged).

**Comment by foobear** [comment]
I could not make out the reason behind the extra blank lines. :)

Personally, I'd prefer dropping them, but am not too attached to that change and could live with extra linebreaks.
Maybe putting a comment into those lines might help clarifying what the following section is about.

**Comment by codener** [comment]
Same for me. I think some comments will help more than extra lines, as there are many subtleties in the examples (i.e. the fat arrow that's required in functions in "controller as" controllers).

**Comment by kratob** [comment]
I've removed all double blank lines and replaced some of them with a comment.

**Pull request closed without merging**
